os: linux
dist: xenial
language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

deploy:
  - provider: releases
    token: ${GH_TOKEN}
    file_glob: true
    file:
      - "*/build/libs/*.jar"
    cleanup: false
    on:
      tags: true
  - provider: script
    script: ./gradlew publish
    cleanup: false
    on:
      branch: dev
  - provider: script
    script: ./gradlew bintrayUpload
    cleanup: false 
    on:
      tags: true
