# Continuous integration, including test and integration test
name: Publish snapshots

# Run in master and dev branches and in all pull requests to those branches
on:
  push:
    branches: [ dev ]

jobs:
  # Build and test the code
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          # Cache gradle directories
          path: |
            ~/.gradle/caches/jars-3
            ~/.gradle/caches/modules-2/files-2.1/
            ~/.gradle/caches/modules-2/metadata-2.96/
            ~/.gradle/native
            ~/.gradle/wrapper
          # Key for restoring and saving the cache
          key: ${{ runner.os }}-gradle

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish
        run: |
          ./gradlew \
            -Possrh.user=${{ secrets.OSSRH_USER }}
            -Possrh.password=${{ secrets.OSSRH_PASSWORD }}
            -Psigning.gnupg.keyName=CBEF2CF0  \
            -Psigning.gnupg.executable=gpg \
            -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}
            publish
