# Create release files
name: Release

on:
    release:
        types: [published]

jobs:
    upload:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Cache
              uses: actions/cache@v2.0.0
              with:
                  # A list of files, directories, and wildcard patterns to cache and restore
                  path: |
                      ~/.gradle/caches/jars-3
                      ~/.gradle/caches/modules-2/files-2.1/
                      ~/.gradle/caches/modules-2/metadata-2.96/
                      ~/.gradle/native
                      ~/.gradle/wrapper
                  # An explicit key for restoring and saving the cache
                  key: ${{ runner.os }}-gradle

            # Compile code
            - name: Compile code
              run: ./gradlew assemble

            # Upload it to GitHub
            - name: Upload to GitHub
              uses: AButler/upload-release-assets@v2.0
              with:
                  files: 'radar-jersey/build/libs/*;radar-jersey-hibernate/build/libs/*'
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install gpg secret key
              run: |
                cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
                gpg --list-secret-keys --keyid-format LONG

            - name: Publish
              run: |
                ./gradlew \
                  -Possrh.user=${{ secrets.OSSRH_USER }}
                  -Possrh.password=${{ secrets.OSSRH_PASSWORD }}
                  -Psigning.gnupg.keyName=CBEF2CF0  \
                  -Psigning.gnupg.executable=gpg \
                  -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}
                  publish
